### ISSUE TITLE
ODR from SAN (need to reproduce + fix)

### ISSUE THREAD

**Issue by mattfidler** [nlmixrdevelopment/RxODE#372]

**Comment by mattfidler** [comment]
```
==136164==ERROR: AddressSanitizer: odr-violation (0x7efd2f2f1240):
  [1] size=168 '__itt__ittapi_global' ../../src/tbb/tools_api/ittnotify_static.c:231:14
  [2] size=168 '__itt__ittapi_global' ../../src/tbb/tools_api/ittnotify_static.c:231:14
These globals were registered at these points:
  [1]:
    #0 0x7efd3c896b78  (/usr/lib/x86_64-linux-gnu/libasan.so.6+0x37b78)
    #1 0x7efd2f24ab91 in _sub_I_00099_1 (/usr/local/RDsan/lib/R/site-library/RcppParallel/lib/libtbbmalloc.so.2+0xd6b91)
    #2 0x7efd3d244dbd  (/lib64/ld-linux-x86-64.so.2+0x11dbd)

  [2]:
    #0 0x7efd3c896b78  (/usr/lib/x86_64-linux-gnu/libasan.so.6+0x37b78)
    #1 0x7efd2f5dec70 in _sub_I_00099_1 (/usr/local/RDsan/lib/R/site-library/RcppParallel/lib/libtbb.so.2+0x240c70)
    #2 0x7efd3d244dbd  (/lib64/ld-linux-x86-64.so.2+0x11dbd)
```

**Comment by mattfidler** [comment]
https://github.com/RcppCore/RcppParallel/issues/152

**Comment by mattfidler** [comment]
Other than that I cannot reproduce any ODR violations.
