### ISSUE TITLE
Crash while trying to fit model with character covariates

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/RxODE#410]
I'm trying to fit a model with covariates that are character strings, and it crashes reproducibly.  This is with nlmixr and RxODE installed from GitHub about 1 hour ago on Windows 10 with R 4.0.3.

```r
library(nlmixr)

test_model_no_sex <- function() {
  ini({
    le0 <- log(1500) ; label("Baseline Phe at age 2 weeks (umol/L)")
    lemax_age <- log(1000) ; label("Mean Phe at steady-state age (umol/L)")
    let50_age <- log(2) ; label("Time after age 2 weeks when half of steady-state age is achieved (weeks)")
    iiv_emax_age ~ 0.1 ; label("IIV in mean Phe at steady-state (log-scale standard deviation)")
    prop_err <- 0.2 ; label("proportional residual error (fraction)")
    add_err <- 1 ; label("additive residual error (umol/L)")
  })
  model({
    e0 <- exp(le0)
    emax_age <- exp(lemax_age + iiv_emax_age)
    et50_age <- exp(let50_age)
    d/dt(EFFECT) = 0
    effect <- e0 + (emax_age - e0)*(NTS_birth - 2)/(et50_age + (NTS_birth - 2))
    effect ~ prop(prop_err) + add(add_err)
  })
}

test_model_sex <- function() {
  ini({
    le0_male <- log(1500) ; label("Baseline Phe at age 2 weeks for males (umol/L)")
    le0_female <- log(2000) ; label("Baseline Phe at age 2 weeks for females (umol/L)")
    lemax_age <- log(1000) ; label("Mean Phe at steady-state age (umol/L)")
    let50_age <- log(2) ; label("Time after age 2 weeks when half of steady-state age is achieved (weeks)")
    iiv_emax_age ~ 0.1 ; label("IIV in mean Phe at steady-state (log-scale standard deviation)")
    prop_err <- 0.2 ; label("proportional residual error (fraction)")
    add_err <- 1 ; label("additive residual error (umol/L)")
  })
  model({
    e0 <- exp(le0_male*(SEX == "M") + le0_female*(SEX == "F"))
    emax_age <- exp(lemax_age + iiv_emax_age)
    et50_age <- exp(let50_age)
    d/dt(EFFECT) = 0
    effect <- e0 + (emax_age - e0)*(NTS_birth - 2)/(et50_age + (NTS_birth - 2))
    effect ~ prop(prop_err) + add(add_err)
  })
}

d_mod <-
  data.frame(
    ID=rep(1:2, each=2),
    CMT="EFFECT",
    DV=1000 + rnorm(4),
    NTS_birth=rep(2:3, 2),
    SEX=rep(c("F", "M"), each=2),
    TIME=1
  )

nlmixr(object=test_model_no_sex, data=d_mod, est="focei") # problems because the data are not real, but no crash
nlmixr(object=test_model_sex, data=d_mod, est="focei") # crashes
```

**Comment by mattfidler** [comment]
Here is the RxODE code to produce the crash:

```R
mod <- RxODE("cmt(EFFECT);\nd/dt(EFFECT)=0;\nd/dt(rx__sens_EFFECT_BY_ETA_1___)=0;\nrx_yj_~2;\nrx_lambda_~1;\nrx_hi_~1;\nrx_low_~0;\nrx_expr_0~exp(THETA[4]);\nrx_expr_1~ETA[1]+THETA[3];\nrx_expr_2~SEX==\"F\";\nrx_expr_3~SEX==\"M\";\nrx_expr_4~exp(rx_expr_1);\nrx_expr_5~(rx_expr_2)*THETA[2];\nrx_expr_6~(rx_expr_3)*THETA[1];\nrx_expr_7~rx_expr_5+rx_expr_6;\nrx_expr_8~exp(rx_expr_7);\nrx_expr_9~rx_expr_4-rx_expr_8;\nrx_expr_10~(-2+NTS_birth)*(rx_expr_9);\nrx_expr_11~rx_expr_10/(-2+NTS_birth+rx_expr_0);\nrx_pred_=rx_expr_11+rx_expr_8;\nrx__sens_rx_pred__BY_ETA_1___=rx_expr_4*(-2+NTS_birth)/(-2+NTS_birth+rx_expr_0);\nrx_r_=Rx_pow_di((THETA[6]+THETA[5]*(rx_expr_11+rx_expr_8)),2);\nrx__sens_rx_r__BY_ETA_1___=2*rx_expr_4*(-2+NTS_birth)*(THETA[6]+THETA[5]*(rx_expr_11+rx_expr_8))*THETA[5]/(-2+NTS_birth+rx_expr_0);\ncmt(effect);\n")

  est <- c("THETA[1]" = 7.3132203870903, "THETA[2]" = 7.60090245954208, "THETA[3]" = 6.90775527898214, "THETA[4]" = 0.693147180559945, "THETA[5]" = 0.2, "THETA[6]" = 1, "ETA[1]" = 0)



  d <-
  data.frame(
    ID=rep(1:2, each=2),
    CMT="EFFECT",
    DV=1000 + rnorm(4),
    NTS_birth=rep(2:3, 2),
    SEX=rep(c("F", "M"), each=2),
    TIME=1
  )

  s <- rxSolve(mod, est, d)

```

**Comment by mattfidler** [comment]
```gdb
#0  0x00007ffff7aae682 in ?? () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fffeea08ea0 in compareFactorVal (val=<optimized out>, 
    valStr=<optimized out>, cmpValue=0x7fffee451000 'F\000')
    at par_solve.cpp:418
#2  0x00007fffee44f7bc in rx_1529513757c4bfed823f9273debd5c6a__calc_lhs (
    _cSub=<optimized out>, __t=<optimized out>, 
    __zzStateVar__=<optimized out>, _lhs=0x555559b130a0)
    at rx_1529513757c4bfed823f9273debd5c6a_.c:534
#3  0x00007fffeea0dc01 in ind_liblsoda0 (
    rx=rx@entry=0x7fffeeb4f200 <rx_global>, 
    op=op@entry=0x7fffeeb4ec60 <op_global>, opt=..., solveid=solveid@entry=0, 
    dydt_liblsoda=<optimized out>, 
    u_inis=0x7fffee44f390 <rx_1529513757c4bfed823f9273debd5c6a__inis>)
    at par_solve.cpp:1979
#4  0x00007fffeea0e12a in par_liblsoda._omp_fn.0(void) ()
    at par_solve.cpp:2049
```

**Comment by mattfidler** [comment]
This should be fixed.  Let me know.

**Comment by billdenney** [comment]
It works for me now.  Thanks!
